image:
  name: hugo-dev:latest

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_PROJECT_NAME: portfolio

pages:
  script:
    - env
    - cd $HUGO_PROJECT_NAME
    - hugo -d ../public --gc --noBuildLock
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "site"