languageCode: ja
languageName: Japanese

title: Zetsubo Engineer

author:
  name: Kotaro Kuroda
  image: image/author.jpg
  headline: くそ現代っ子ごみかす20代
  links:
    - github: https://github.com/jolly96k
    - gitlab: https://rm.zetsubo.net/jolly96k