enableSearch: false

homepage:
  showRecent: true

article:
  showDateUpdated: true
  showBreadcrumbs: true
  showReadingTime: false
  showTableOfContents: true
  showWordCount: false
  sharingLinks:
    - linkedin
    - twitter
    - reddit
    - pinterest
    - facebook
    - email
    - whatsapp

list:
  showBreadcrumbs: true
  showTableOfContents: true